-- ============================================================================
-- BoostTribe — Demandes d'accès gratuit à une session payante (« Demander l'accès »)
-- À exécuter en supabase_admin. Idempotent.
-- ============================================================================

-- 1) Toggle coach sur la page promo : autoriser les demandes d'accès gratuit.
alter table public.playlists
  add column if not exists promo_allow_access_requests boolean default false;

-- 2) Table des demandes d'accès.
create table if not exists public.access_requests (
  id                bigint generated by default as identity primary key,
  session_id        text not null,
  requester_user_id uuid,
  requester_name    text not null,
  status            text not null default 'pending',  -- pending | approved | refused
  created_at        timestamptz not null default now(),
  decided_at        timestamptz
);
create index if not exists access_requests_session_idx on public.access_requests (session_id, status);

alter table public.access_requests enable row level security;

-- 3) RLS :
--    - l'HÔTE de la session lit/écrit ses demandes (host_id de playlists) ;
--    - le DEMANDEUR lit la sienne ;
--    - les écritures « métier » passent par le backend (service_role, bypass RLS).
drop policy if exists access_requests_host_select on public.access_requests;
create policy access_requests_host_select on public.access_requests for select to authenticated
using (
  exists (select 1 from public.playlists p where p.session_id = access_requests.session_id and p.host_id = auth.uid())
  or requester_user_id = auth.uid()
);

drop policy if exists access_requests_host_update on public.access_requests;
create policy access_requests_host_update on public.access_requests for update to authenticated
using (exists (select 1 from public.playlists p where p.session_id = access_requests.session_id and p.host_id = auth.uid()))
with check (exists (select 1 from public.playlists p where p.session_id = access_requests.session_id and p.host_id = auth.uid()));

-- 4) Realtime : l'hôte est notifié en temps réel des nouvelles demandes.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'access_requests'
  ) then
    alter publication supabase_realtime add table public.access_requests;
  end if;
end $$;
