/**
 * RÉSOLUTION LUE DANS L'EN-TÊTE DU FICHIER — banc PUR sur de VRAIES premières tranches de MediaRecorder
 * (Google Chrome 153, macOS, 21/09/2026, sources canvas 1280×720 et 1920×1080 + oscillateur audio) :
 *  - MP4 (`video/mp4;codecs=avc1…,mp4a.40.2`) : 1re tranche = `ftyp + moov` (1 243 / 1 245 octets), aucune image ;
 *  - WebM (`video/webm;codecs=vp9,opus`) : EBML + Segment + Info + Tracks, tronqué avant le 1er Cluster (208 octets).
 * C'est exactement ce que ffprobe lit (`stream=width,height`) : la fonction doit y coïncider par construction.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { resolutionFichier, resolutionMp4, resolutionWebm } from './.build/resolutionFichier.mjs';

const octets = (b64) => new Uint8Array(Buffer.from(b64, 'base64'));
const MP4_720 = 'AAAAJGZ0eXBpc29tAAACAGlzb21pc282aXNvMmF2YzFtcDQxAAAEt21vb3YAAAB4bXZoZAEAAAAAAAAA5talBAAAAADm1qUEAAAD6AAAAAAAAAnHAAEAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAIgdHJhawAAAGh0a2hkAQAAAwAAAADm1qUEAAAAAObWpQQAAAABAAAAAAAAAAAAAAnHAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAUAAAAC0AAAAAABsG1kaWEAAAAsbWRoZAEAAAAAAAAA5talBAAAAADm1qUEAAB1MAAAAAAAAAnHVcQAAAAAAC1oZGxyAAAAAAAAAAB2aWRlAAAAAAAAAAAAAAAAVmlkZW9IYW5kbGVyAAAAAU9taW5mAAAAFHZtaGQAAAABAAAAAAAAAAAAAAAlZGluZgAAAB1kcmVmAAAAAAAAAAEAAAANdXJsIAAAAAEAAAABDnN0YmwAAAAQc3RzYwAAAAAAAAAAAAAAEHN0dHMAAAAAAAAAAAAAABRzdHN6AAAAAAAAAAAAAAAAAAAAEHN0Y28AAAAAAAAAAAAAAMJzdHNkAAAAAAAAAAEAAACyYXZjMQAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAUAAtAASAAAAEgAAAAAAAAAAQtBVkMxIENvZGluZwAAAAAAAAAAAAAAAAAAAAAAAAAAABj//wAAABBwYXNwAAAAAQAAAAEAAAAUYnRydAAAAAAAAAAAAAAAAAAAACVhdmNDAUIAH//hAA4nQgAfq0AoAt03AQ0BAgEABCjOPIAAAAATY29scm5jbHgAAQANAAGAAAABz3RyYWsAAABodGtoZAEAAAMAAAAA5talBAAAAADm1qUEAAAAAgAAAAAAAAAAAAAJqgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAV9tZGlhAAAALG1kaGQBAAAAAAAAAObWpQQAAAAA5talBAAAu4AAAAAAAAAJqlXEAAAAAAAtaGRscgAAAAAAAAAAc291bgAAAAAAAAAAAAAAAFNvdW5kSGFuZGxlcgAAAAD+bWluZgAAABBzbWhkAAAAAAAAAAAAAAAlZGluZgAAAB1kcmVmAAAAAAAAAAEAAAANdXJsIAAAAAEAAAAAwXN0YmwAAAAQc3RzYwAAAAAAAAAAAAAAEHN0dHMAAAAAAAAAAAAAABRzdHN6AAAAAAAAAAAAAAAAAAAAEHN0Y28AAAAAAAAAAAAAAHVzdHNkAAAAAAAAAAEAAABlbXA0YQAAAAAAAAABAAAAAAAAAAAAAgAQAAAAALuAAAAAAAAUYnRydAAAAAAAAAAAAAAAAAAAAC1lc2RzAAAAAAOAgIAcAAAABICAgBRAFQAAAAAAAAAAAAAABYCAgAIRkAAAAEhtdmV4AAAAIHRyZXgAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAgdHJleAAAAAAAAAACAAAAAQAAAAAAAAAAAAAAAA==';
const MP4_1080 = 'AAAAJGZ0eXBpc29tAAACAGlzb21pc282aXNvMmF2YzFtcDQxAAAEuW1vb3YAAAB4bXZoZAEAAAAAAAAA5talBwAAAADm1qUHAAAD6AAAAAAAAAm/AAEAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAHPdHJhawAAAGh0a2hkAQAAAwAAAADm1qUHAAAAAObWpQcAAAABAAAAAAAAAAAAAAm/AAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABX21kaWEAAAAsbWRoZAEAAAAAAAAA5talBwAAAADm1qUHAAC7gAAAAAAAAAm/VcQAAAAAAC1oZGxyAAAAAAAAAABzb3VuAAAAAAAAAAAAAAAAU291bmRIYW5kbGVyAAAAAP5taW5mAAAAEHNtaGQAAAAAAAAAAAAAACVkaW5mAAAAHWRyZWYAAAAAAAAAAQAAAA11cmwgAAAAAQAAAADBc3RibAAAABBzdHNjAAAAAAAAAAAAAAAQc3R0cwAAAAAAAAAAAAAAFHN0c3oAAAAAAAAAAAAAAAAAAAAQc3RjbwAAAAAAAAAAAAAAdXN0c2QAAAAAAAAAAQAAAGVtcDRhAAAAAAAAAAEAAAAAAAAAAAACABAAAAAAu4AAAAAAABRidHJ0AAAAAAAAAAAAAAAAAAAALWVzZHMAAAAAA4CAgBwAAAAEgICAFEAVAAAAAAAAAAAAAAAFgICAAhGQAAACInRyYWsAAABodGtoZAEAAAMAAAAA5talBwAAAADm1qUHAAAAAgAAAAAAAAAAAAAJogAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAHgAAABDgAAAAAAbJtZGlhAAAALG1kaGQBAAAAAAAAAObWpQcAAAAA5talBwAAdTAAAAAAAAAJolXEAAAAAAAtaGRscgAAAAAAAAAAdmlkZQAAAAAAAAAAAAAAAFZpZGVvSGFuZGxlcgAAAAFRbWluZgAAABR2bWhkAAAAAQAAAAAAAAAAAAAAJWRpbmYAAAAdZHJlZgAAAAAAAAABAAAADXVybCAAAAABAAAAARBzdGJsAAAAEHN0c2MAAAAAAAAAAAAAABBzdHRzAAAAAAAAAAAAAAAUc3RzegAAAAAAAAAAAAAAAAAAABBzdGNvAAAAAAAAAAAAAADEc3RzZAAAAAAAAAABAAAAtGF2YzEAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAHgAQ4AEgAAABIAAAAAAAAAAELQVZDMSBDb2RpbmcAAAAAAAAAAAAAAAAAAAAAAAAAAAAY//8AAAAQcGFzcAAAAAEAAAABAAAAFGJ0cnQAAAAAAAAAAAAAAAAAAAAnYXZjQwFCACj/4QAQJ0IAKKtAPAET8s3AQ0BAgAEABCjOPIAAAAATY29scm5jbHgAAQANAAGAAAAASG12ZXgAAAAgdHJleAAAAAAAAAACAAAAAQAAAAAAAAAAAAAAAAAAACB0cmV4AAAAAAAAAAEAAAABAAAAAAAAAAAAAAAA';
const WEBM_720 = 'GkXfo59ChoEBQveBAULygQRC84EIQoKEd2VibUKHgQRChYECGFOAZwH/////////FUmpZpkq17GDD0JATYCGQ2hyb21lV0GGQ2hyb21lFlSua/2uvNeBAXPFhxyKrpUCuRWDgQFV7oEBhoVWX1ZQOeCfsIIFALqCAtBTwIEBVbCQVbGBAVW5gQJVuoENVbuBAa6914ECc8WHov8ktQllBoOBAoaGQV9PUFVTY6KTT3B1c0hlYWQBAgAAgLsAAAAAAOGNtYRHO4AAn4ECYmSBIA==';

test('MP4 Chrome, canvas 1280×720 : stsd/avc1 → 1280×720', () => {
  assert.deepEqual(resolutionFichier(octets(MP4_720), 'mp4'), { width: 1280, height: 720 });
});

test('MP4 Chrome, canvas 1920×1080 : stsd/avc1 → 1920×1080', () => {
  assert.deepEqual(resolutionFichier(octets(MP4_1080), 'mp4'), { width: 1920, height: 1080 });
});

test('la marque « avc1 » de ftyp (offset 28) n’est PAS confondue avec l’entrée stsd (piège mesuré)', () => {
  const u = octets(MP4_720);
  assert.equal(String.fromCharCode(...u.subarray(28, 32)), 'avc1', 'la marque est bien là, à l’offset 28');
  assert.deepEqual(resolutionMp4(u), { width: 1280, height: 720 });
});

test('WebM Chrome, canvas 1280×720 : Tracks/TrackEntry/Video/PixelWidth+PixelHeight → 1280×720', () => {
  assert.deepEqual(resolutionFichier(octets(WEBM_720), 'webm'), { width: 1280, height: 720 });
  assert.deepEqual(resolutionWebm(octets(WEBM_720)), { width: 1280, height: 720 });
});

test('structure inattendue → null, jamais une valeur inventée ni une exception', () => {
  assert.equal(resolutionFichier(new Uint8Array(0), 'mp4'), null);
  assert.equal(resolutionFichier(new Uint8Array(0), 'webm'), null);
  assert.equal(resolutionFichier(new Uint8Array(64).fill(0x41), 'mp4'), null);
  assert.equal(resolutionFichier(new Uint8Array(64).fill(0x41), 'webm'), null);
  assert.equal(resolutionFichier(octets(MP4_720).subarray(0, 300), 'mp4'), null, 'moov tronqué');
  assert.equal(resolutionFichier(octets(WEBM_720).subarray(0, 100), 'webm'), null, 'Tracks tronqué');
  assert.equal(resolutionFichier(octets(MP4_720), 'webm'), null, 'mauvais conteneur');
  assert.equal(resolutionFichier(octets(WEBM_720), 'mp4'), null, 'mauvais conteneur');
});
